import type { ReactNode } from 'react';
import type { ToastAction, ToastVariant } from '../Toast';

/**
 * Toast payload as understood by the Toaster orchestration layer.
 * Mirrors the prop surface of the Toast component (variant, action) plus
 * the orchestration-only fields (id, dismissAfter).
 */
export interface ToastSpec {
  /** Stable identifier — generated by `showToast` if the consumer doesn't
   *  pass one. Used as the React key and for programmatic dismissal. */
  id?: string;
  /** Toast body. Plain string or any ReactNode. */
  message: ReactNode;
  /** Visual variant — defaults to 'success'. */
  variant?: ToastVariant;
  /** Time in ms before auto-dismiss. Defaults to 2400 (matches the
   *  prior inline implementation). Set to 0 to disable auto-dismiss. */
  dismissAfter?: number;
  /** Optional action button — passed through to Toast verbatim. */
  action?: ToastAction;
}

export interface ActiveToast extends ToastSpec {
  /** Always-set after enqueue (showToast generates one if not provided). */
  id: string;
}

export interface ToastContextValue {
  toasts: ActiveToast[];
  showToast: (spec: ToastSpec) => string;
  dismissToast: (id: string) => void;
}

export interface ToasterProviderProps {
  children: ReactNode;
}

export interface ToasterProps {
  /** Optional className for the portal container. */
  className?: string;
}
